### ISSUE TITLE
Slick2D implementation [Discussion]

### ISSUE THREAD

**Issue by kylecbrodie** [Maescool/Catacomb-Snatch#979]
I am currently working on implementing Catacomb Snatch in Slick2D so we can get accelerated graphics (see my [slick](https://github.com/KyleBrodie/Catacomb-Snatch/tree/slick) branch). But there is one thing that I want your opinion on.
So in Slick2D the game updates happen in a `void update(int delta);` method that provides the milliseconds that have passed since the last update. So I was wondering, should I accumulate that delta and then run the tick() for every 16ms, or should we add an `update(int delta);` method to all classes?

I am leaning more towards using just `update(int delta);` but I want to find out what you guys think. here are the pros and cons I thought of.

### Pros
* no need to rewrite the game logic (BIG pro)

### Cons
* the game doesn't know what platform it is on; (will have to provide all the same methods as the old version; duplicate & possibly inefficient code)
* may be less efficient than `update`; (builds up an "update" stack multiple time because of the multiple invocations of `tick`)
* forces 60 updates a second

### Pros
* allows for Slick to selectively slow down or speed up the logic updates (min: 30 max: 60 updates a second)
* works on one "update" stack (may be more efficient)
* lets the game know it is working with a different implementation (allows us to use methods and classes that have been rewritten to be more idiomatic Slick/more efficient)

### Cons
* requires a rewrite of the game logic to work on time deltas. (though a lot will copied and pasted)
* duplicate code (until we completely ditch the old code)

Also just to make sure you know this; this won't affect the rendering process as there will be two render methods. One for software based and one for Slick2D (OpenGL). So that we can provide the option to the player to use either. (I guess if their computer doesn't support OpenGL? or if Slick2D/OpenGL is acting up? those are only two reason I can think of for keeping the software based renderer).

**Comment by Maescool** [comment]
Closing this, this branch is LWJGL and the https://github.com/Catacomb-Snatch/Catacomb-Snatch is the LibGDX version
